apiVersion: v1
kind: ConfigMap
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: test
deploy:
  kubectl:
    manifests:
    - manifests/deployment.yaml
    - manifests/service.yaml
    - manifests/configmap.yaml
