apiVersion: v1
kind: Service
metadata:
  name: hello-python
  namespace: hello-python
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: NodePort
